#include <DueFlashStorage.h>
DueFlashStorage dueFlashStorage;

void save() {
  //saveprog
  int kezdocim = saveprog * 300;
  dueFlashStorage.write(kezdocim, op1waveform);
  dueFlashStorage.write(kezdocim + 2, op2waveform);
  dueFlashStorage.write(kezdocim + 4, op3waveform);
  dueFlashStorage.write(kezdocim + 6, op4waveform);
  dueFlashStorage.write(kezdocim + 8, op5waveform);
  dueFlashStorage.write(kezdocim + 10, op6waveform);
  dueFlashStorage.write(kezdocim + 12, op1al);
  dueFlashStorage.write(kezdocim + 14, op2al);
  dueFlashStorage.write(kezdocim + 16, op3al);
  dueFlashStorage.write(kezdocim + 18, op4al);
  dueFlashStorage.write(kezdocim + 20, op5al);
  dueFlashStorage.write(kezdocim + 22, op6al);
  dueFlashStorage.write(kezdocim + 24, op1ar);
  dueFlashStorage.write(kezdocim + 26, op2ar);
  dueFlashStorage.write(kezdocim + 28, op3ar);
  dueFlashStorage.write(kezdocim + 30, op4ar);
  dueFlashStorage.write(kezdocim + 32, op5ar);
  dueFlashStorage.write(kezdocim + 34, op6ar);
  dueFlashStorage.write(kezdocim + 36, op1d1l);
  dueFlashStorage.write(kezdocim + 38, op2d1l);
  dueFlashStorage.write(kezdocim + 40, op3d1l);
  dueFlashStorage.write(kezdocim + 42, op4d1l);
  dueFlashStorage.write(kezdocim + 44, op5d1l);
  dueFlashStorage.write(kezdocim + 46, op6d1l);
  dueFlashStorage.write(kezdocim + 48, op1d1r);
  dueFlashStorage.write(kezdocim + 50, op2d1r);
  dueFlashStorage.write(kezdocim + 52, op3d1r);
  dueFlashStorage.write(kezdocim + 54, op4d1r);
  dueFlashStorage.write(kezdocim + 56, op5d1r);
  dueFlashStorage.write(kezdocim + 58, op6d1r);
  dueFlashStorage.write(kezdocim + 60, op1d2l);
  dueFlashStorage.write(kezdocim + 62, op2d2l);
  dueFlashStorage.write(kezdocim + 64, op3d2l);
  dueFlashStorage.write(kezdocim + 66, op4d2l);
  dueFlashStorage.write(kezdocim + 68, op5d2l);
  dueFlashStorage.write(kezdocim + 70, op6d2l);
  dueFlashStorage.write(kezdocim + 72, op1d2r);
  dueFlashStorage.write(kezdocim + 74, op2d2r);
  dueFlashStorage.write(kezdocim + 76, op3d2r);
  dueFlashStorage.write(kezdocim + 78, op4d2r);
  dueFlashStorage.write(kezdocim + 80, op5d2r);
  dueFlashStorage.write(kezdocim + 82, op6d2r);
  dueFlashStorage.write(kezdocim + 84, op1rl);
  dueFlashStorage.write(kezdocim + 86, op2rl);
  dueFlashStorage.write(kezdocim + 88, op3rl);
  dueFlashStorage.write(kezdocim + 90, op4rl);
  dueFlashStorage.write(kezdocim + 92, op5rl);
  dueFlashStorage.write(kezdocim + 94, op6rl);
  dueFlashStorage.write(kezdocim + 96, op1rr);
  dueFlashStorage.write(kezdocim + 98, op2rr);
  dueFlashStorage.write(kezdocim + 100, op3rr);
  dueFlashStorage.write(kezdocim + 102, op4rr);
  dueFlashStorage.write(kezdocim + 104, op5rr);
  dueFlashStorage.write(kezdocim + 106, op6rr);
  dueFlashStorage.write(kezdocim + 108, pichal);
  dueFlashStorage.write(kezdocim + 110, pichar);
  dueFlashStorage.write(kezdocim + 112, pichd1l);
  dueFlashStorage.write(kezdocim + 114, pichd1r);
  dueFlashStorage.write(kezdocim + 116, pichd2l);
  dueFlashStorage.write(kezdocim + 118, pichd2r);
  dueFlashStorage.write(kezdocim + 120, pichrl);
  dueFlashStorage.write(kezdocim + 122, pichrr);
  dueFlashStorage.write(kezdocim + 124, op1volume );
  dueFlashStorage.write(kezdocim + 126, op2volume );
  dueFlashStorage.write(kezdocim + 128, op3volume );
  dueFlashStorage.write(kezdocim + 130, op4volume );
  dueFlashStorage.write(kezdocim + 132, op5volume );
  dueFlashStorage.write(kezdocim + 134, op6volume );
  dueFlashStorage.write(kezdocim + 136, op1veloc );
  dueFlashStorage.write(kezdocim + 138, op2veloc );
  dueFlashStorage.write(kezdocim + 140, op3veloc );
  dueFlashStorage.write(kezdocim + 142, op4veloc );
  dueFlashStorage.write(kezdocim + 144, op5veloc );
  dueFlashStorage.write(kezdocim + 146, op6veloc );
  dueFlashStorage.write(kezdocim + 148, op1generatorfreq );
  dueFlashStorage.write(kezdocim + 150, op2generatorfreq );
  dueFlashStorage.write(kezdocim + 152, op3generatorfreq );
  dueFlashStorage.write(kezdocim + 154, op4generatorfreq );
  dueFlashStorage.write(kezdocim + 156, op5generatorfreq );
  dueFlashStorage.write(kezdocim + 158, op6generatorfreq );
  dueFlashStorage.write(kezdocim + 160, fixfreqstep );
  dueFlashStorage.write(kezdocim + 162, (op1generatorfreqfix));
  dueFlashStorage.write(kezdocim + 166, (op2generatorfreqfix));
  dueFlashStorage.write(kezdocim + 170, (op3generatorfreqfix));
  dueFlashStorage.write(kezdocim + 174, (op4generatorfreqfix));
  dueFlashStorage.write(kezdocim + 178, (op5generatorfreqfix));
  dueFlashStorage.write(kezdocim + 182, (op6generatorfreqfix));
  dueFlashStorage.write(kezdocim + 184, pichop1 );
  dueFlashStorage.write(kezdocim + 186, pichop2 );
  dueFlashStorage.write(kezdocim + 188, pichop3 );
  dueFlashStorage.write(kezdocim + 190, pichop4 );
  dueFlashStorage.write(kezdocim + 192, pichop5 );
  dueFlashStorage.write(kezdocim + 194, pichop6 );
  dueFlashStorage.write(kezdocim + 196, notefixedop1 );
  dueFlashStorage.write(kezdocim + 198, notefixedop2 );
  dueFlashStorage.write(kezdocim + 200, notefixedop3 );
  dueFlashStorage.write(kezdocim + 202, notefixedop4 );
  dueFlashStorage.write(kezdocim + 204, notefixedop5 );
  dueFlashStorage.write(kezdocim + 206, notefixedop6 );
  dueFlashStorage.write(kezdocim + 208,  frame );
  dueFlashStorage.write(kezdocim + 210,   szorzo );
  dueFlashStorage.write(kezdocim + 212,   alg );
  dueFlashStorage.write(kezdocim + 214,   level );
  dueFlashStorage.write(kezdocim + 216,   pichkezd );
  dueFlashStorage.write(kezdocim + 218,   picheglevel);
//  dueFlashStorage.write(kezdocim + 222,  oplfo );
  dueFlashStorage.write(kezdocim + 224,  oplfo2max );
  dueFlashStorage.write(kezdocim + 226,  oplfo4max );
  dueFlashStorage.write(kezdocim + 228,  oplfo6max );
  dueFlashStorage.write(kezdocim + 230,  lfo2step );
  dueFlashStorage.write(kezdocim + 232,  lfo4step );
  dueFlashStorage.write(kezdocim + 234,  lfo6step );
  dueFlashStorage.write(kezdocim + 236,  lfo1step );
  dueFlashStorage.write(kezdocim + 238,  lfo1max );
  dueFlashStorage.write(kezdocim + 240,  lfo1min );//!!!
  dueFlashStorage.write(kezdocim + 242,  eqvalue );
  dueFlashStorage.write(kezdocim + 244,  lfo2freq);
  dueFlashStorage.write(kezdocim + 246,  reverblevel );
  dueFlashStorage.write(kezdocim + 248,  reverbtime);
  dueFlashStorage.write(kezdocim + 250,  reverblevel2 );
  dueFlashStorage.write(kezdocim + 252,  reverbtime2 );
  dueFlashStorage.write(kezdocim + 254,  gorbeszorzo);
  dueFlashStorage.write(kezdocim + 256,  released);
  dueFlashStorage.write(kezdocim + 258,  chorusfreq);
  dueFlashStorage.write(kezdocim + 260,  choruslevel);
}

void load(byte loadprog) {
  int kezdocim = loadprog * 300;
  op1waveform = dueFlashStorage.read(kezdocim + 0);
  op2waveform = dueFlashStorage.read(kezdocim + 2);
  op3waveform = dueFlashStorage.read(kezdocim + 3);
  op4waveform = dueFlashStorage.read(kezdocim + 6);
  op5waveform = dueFlashStorage.read(kezdocim + 8);
  op6waveform = dueFlashStorage.read(kezdocim + 10);
  op1al = dueFlashStorage.read(kezdocim + 12);
  op2al = dueFlashStorage.read(kezdocim + 14);
  op3al = dueFlashStorage.read(kezdocim + 16);
  op4al = dueFlashStorage.read(kezdocim + 18);
  op5al = dueFlashStorage.read(kezdocim + 20);
  op6al = dueFlashStorage.read(kezdocim + 22);
  op1ar = dueFlashStorage.read(kezdocim + 24);
  op2ar = dueFlashStorage.read(kezdocim + 26);
  op3ar = dueFlashStorage.read(kezdocim + 28);
  op4ar = dueFlashStorage.read(kezdocim + 30);
  op5ar = dueFlashStorage.read(kezdocim + 32);
  op6ar = dueFlashStorage.read(kezdocim + 34);
  op1d1l = dueFlashStorage.read(kezdocim + 36);
  op2d1l = dueFlashStorage.read(kezdocim + 38);
  op3d1l = dueFlashStorage.read(kezdocim + 40);
  op4d1l = dueFlashStorage.read(kezdocim + 42);
  op5d1l = dueFlashStorage.read(kezdocim + 44);
  op6d1l = dueFlashStorage.read(kezdocim + 46);
  op1d1r = dueFlashStorage.read(kezdocim + 48);
  op2d1r = dueFlashStorage.read(kezdocim + 50);
  op3d1r = dueFlashStorage.read(kezdocim + 52);
  op4d1r = dueFlashStorage.read(kezdocim + 54);
  op5d1r = dueFlashStorage.read(kezdocim + 56);
  op6d1r = dueFlashStorage.read(kezdocim + 58);
  op1d2l = dueFlashStorage.read(kezdocim + 60);
  op2d2l = dueFlashStorage.read(kezdocim + 62);
  op3d2l = dueFlashStorage.read(kezdocim + 64);
  op4d2l = dueFlashStorage.read(kezdocim + 66);
  op5d2l = dueFlashStorage.read(kezdocim + 68);
  op6d2l = dueFlashStorage.read(kezdocim + 70);
  op1d2r = dueFlashStorage.read(kezdocim + 72);
  op2d2r = dueFlashStorage.read(kezdocim + 74);
  op3d2r = dueFlashStorage.read(kezdocim + 76);
  op4d2r = dueFlashStorage.read(kezdocim + 78);
  op5d2r = dueFlashStorage.read(kezdocim + 80);
  op6d2r = dueFlashStorage.read(kezdocim + 82 );
  op1rl = dueFlashStorage.read(kezdocim + 84);
  op2rl = dueFlashStorage.read(kezdocim + 86);
  op3rl = dueFlashStorage.read(kezdocim + 88);
  op4rl = dueFlashStorage.read(kezdocim + 90);
  op5rl = dueFlashStorage.read(kezdocim + 92);
  op6rl = dueFlashStorage.read(kezdocim + 94);
  op1rr = dueFlashStorage.read(kezdocim + 96);
  op2rr = dueFlashStorage.read(kezdocim + 98);
  op3rr = dueFlashStorage.read(kezdocim + 100);
  op4rr = dueFlashStorage.read(kezdocim + 102);
  op5rr = dueFlashStorage.read(kezdocim + 104);
  op6rr = dueFlashStorage.read(kezdocim + 106);
  pichal = dueFlashStorage.read(kezdocim + 108);
  pichar = dueFlashStorage.read(kezdocim + 110);
  pichd1l = dueFlashStorage.read(kezdocim + 112);
  pichd1r = dueFlashStorage.read(kezdocim + 114);
  pichd2l = dueFlashStorage.read(kezdocim + 116);
  pichd2r = dueFlashStorage.read(kezdocim + 118);
  pichrl = dueFlashStorage.read(kezdocim + 120);
  pichrr = dueFlashStorage.read(kezdocim + 122);
  op1volume = dueFlashStorage.read(kezdocim + 124);
  op2volume = dueFlashStorage.read(kezdocim + 126);
  op3volume = dueFlashStorage.read(kezdocim + 128);
  op4volume = dueFlashStorage.read(kezdocim + 130);
  op5volume = dueFlashStorage.read(kezdocim + 132);
  op6volume = dueFlashStorage.read(kezdocim + 134);
  op1veloc = dueFlashStorage.read(kezdocim + 136);
  op2veloc = dueFlashStorage.read(kezdocim + 138);
  op3veloc = dueFlashStorage.read(kezdocim + 140);
  op4veloc = dueFlashStorage.read(kezdocim + 142);
  op5veloc = dueFlashStorage.read(kezdocim + 144);
  op6veloc = dueFlashStorage.read(kezdocim + 146);
  op1generatorfreq = dueFlashStorage.read(kezdocim + 148);
  op2generatorfreq = dueFlashStorage.read(kezdocim + 150);
  op3generatorfreq = dueFlashStorage.read(kezdocim + 152);
  op4generatorfreq = dueFlashStorage.read(kezdocim + 154);
  op5generatorfreq = dueFlashStorage.read(kezdocim + 156);
  op6generatorfreq = dueFlashStorage.read(kezdocim + 158);
  fixfreqstep = dueFlashStorage.read(kezdocim + 160);
  op1generatorfreqfix  = dueFlashStorage.read(kezdocim + 162);
  op2generatorfreqfix  = dueFlashStorage.read(kezdocim + 166);
  op3generatorfreqfix  = dueFlashStorage.read(kezdocim + 170);
  op4generatorfreqfix  = dueFlashStorage.read(kezdocim + 174);
  op5generatorfreqfix  = dueFlashStorage.read(kezdocim + 178);
  op6generatorfreqfix  = dueFlashStorage.read(kezdocim + 182);
  pichop1  = dueFlashStorage.read(kezdocim + 184);
  pichop2  = dueFlashStorage.read(kezdocim + 186);
  pichop3  = dueFlashStorage.read(kezdocim + 188);
  pichop4  = dueFlashStorage.read(kezdocim + 190);
  pichop5  = dueFlashStorage.read(kezdocim + 192);
  pichop6  = dueFlashStorage.read(kezdocim + 194);
  notefixedop1  = dueFlashStorage.read(kezdocim + 196);
  notefixedop2  = dueFlashStorage.read(kezdocim + 198);
  notefixedop3  = dueFlashStorage.read(kezdocim + 200);
  notefixedop4  = dueFlashStorage.read(kezdocim + 202);
  notefixedop5  = dueFlashStorage.read(kezdocim + 204);
  notefixedop6  = dueFlashStorage.read(kezdocim + 206);
  frame  = dueFlashStorage.read(kezdocim + 208);
  szorzo  = dueFlashStorage.read(kezdocim + 210);
  alg  = dueFlashStorage.read(kezdocim + 212);
  level  = dueFlashStorage.read(kezdocim + 214);
  pichkezd  = dueFlashStorage.read(kezdocim + 216);
  picheglevel  = dueFlashStorage.read(kezdocim + 218);
//  oplfo  = dueFlashStorage.read(kezdocim + 222);
  oplfo2max  = dueFlashStorage.read(kezdocim + 224);
  oplfo4max  = dueFlashStorage.read(kezdocim + 226);
  oplfo6max  = dueFlashStorage.read(kezdocim + 228);
  lfo2step  = dueFlashStorage.read(kezdocim + 230);
  lfo4step  = dueFlashStorage.read(kezdocim + 232);
  lfo6step  = dueFlashStorage.read(kezdocim + 234);
  lfo1step  = dueFlashStorage.read(kezdocim + 236);
  lfo1max = dueFlashStorage.read(kezdocim + 238);
  lfo1min  = dueFlashStorage.read(kezdocim + 240);
  eqvalue  = dueFlashStorage.read(kezdocim + 242);
  lfo2freq  = dueFlashStorage.read(kezdocim + 244);
  reverblevel  = dueFlashStorage.read(kezdocim + 246);
  reverbtime  = dueFlashStorage.read(kezdocim + 248);
  reverblevel2  = dueFlashStorage.read(kezdocim + 250);
  reverbtime2  = dueFlashStorage.read(kezdocim + 252);
  gorbeszorzo = dueFlashStorage.read(kezdocim + 254);
  released  = dueFlashStorage.read(kezdocim + 256);
  chorusfreq = dueFlashStorage.read(kezdocim + 258);
  choruslevel  = dueFlashStorage.read(kezdocim + 260);
}
